# Generated by Django 4.2.7 on 2023-12-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=5)),
                ('matn', models.TextField()),
                ('vaqt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
