# Generated by Django 4.2.7 on 2023-12-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ish',
            name='nomi',
            field=models.CharField(max_length=20),
        ),
    ]
